// user
export const GET_SIGNIN_USER_SUCCESS = "GET_SIGNIN_USER_SUCCESS"
export const GET_SIGNIN_USER_REQUEST = "GET_SIGNIN_USER_REQUEST"
export const GET_SIGNIN_USER_ERROR = "GET_SIGNIN_USER_ERROR"

export const GET_CLINIC_LIST_REQUEST = "GET_CLINIC_LIST_REQUEST"
export const GET_CLINIC_LIST_SUCCESS = "GET_CLINIC_LIST_SUCCESS"
export const GET_CLINIC_LIST_ERROR = "GET_CLINIC_LIST_ERROR"

export const GET_ADD_USER_REQUEST = "GET_ADD_USER_REQUEST"
export const GET_ADD_USER_SUCCESS = "GET_ADD_USER_SUCCESS"
export const GET_ADD_USER_ERROR = "GET_ADD_USER_ERROR"

export const GET_UPDATE_USER_REQUEST = "GET_UPDATE_USER_REQUEST"
export const GET_UPDATE_USER_SUCCESS = "GET_UPDATE_USER_SUCCESS"
export const GET_UPDATE_USER_ERROR = "GET_UPDATE_USER_ERROR"

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST"
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS"
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR"

export const GET_USER_DETAIL_REQUEST = "GET_USER_DETAIL_REQUEST"
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS"
export const GET_USER_DETAIL_ERROR = "GET_USER_DETAIL_ERROR"


export const GET_USER_STATUS_REQUEST = "GET_USER_STATUS_REQUEST"
export const GET_USER_STATUS_SUCCESS = "GET_USER_STATUS_SUCCESS"
export const GET_USER_STATUS_ERROR = "GET_USER_STATUS_ERROR"

export const GET_CLINIC_CHANGE_STATUS_REQUEST = "GET_CLINIC_CHANGE_STATUS_REQUEST"
export const GET_CLINIC_CHANGE_STATUS_SUCCESS = "GET_CLINIC_CHANGE_STATUS_SUCCESS"
export const GET_CLINIC_CHANGE_STATUS_ERROR = "GET_CLINIC_CHANGE_STATUS_ERROR"



export const GET_SUBSCRIPTION_CHANGE_STATUS_REQUEST = "GET_SUBSCRIPTION_CHANGE_STATUS_REQUEST"
export const GET_SUBSCRIPTION_CHANGE_STATUS_SUCCESS = "GET_SUBSCRIPTION_CHANGE_STATUS_SUCCESS"
export const GET_SUBSCRIPTION_CHANGE_STATUS_ERROR = "GET_SUBSCRIPTION_CHANGE_STATUS_ERROR"

export const GET_CLINIC_SUBSCRIPTION_REQUEST = "GET_CLINIC_SUBSCRIPTION_REQUEST"
export const GET_CLINIC_SUBSCRIPTION_SUCCESS = "GET_CLINIC_SUBSCRIPTION_SUCCESS"
export const GET_CLINIC_SUBSCRIPTION_ERROR = "GET_CLINIC_SUBSCRIPTION_ERROR"
//MASTER

export const GET_UPDATE_TERMCONDITION_REQUEST = "GET_UPDATE_TERMCONDITION_REQUEST"
export const GET_UPDATE_TERMCONDITION_SUCCESS = "GET_UPDATE_TERMCONDITION_SUCCESS"
export const GET_UPDATE_TERMCONDITION_ERROR = "GET_UPDATE_TERMCONDITION_ERROR"

export const GET_TERMCONDITION_LIST_REQUEST = "GET_TERMCONDITION_LIST_REQUEST"
export const GET_TERMCONDITION_LIST_SUCCESS = "GET_TERMCONDITION_LIST_SUCCESS"
export const GET_TERMCONDITION_LIST_ERROR = "GET_TERMCONDITION_LIST_ERROR"

export const GET_STATE_LIST_REQUEST = "GET_STATE_LIST_REQUEST"
export const GET_STATE_LIST_SUCCESS = "GET_STATE_LIST_SUCCESS"
export const GET_STATE_LIST_ERROR = "GET_STATE_LIST_ERROR"

export const GET_COUNTRY_LIST_REQUEST = "GET_COUNTRY_LIST_REQUEST"
export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS"
export const GET_COUNTRY_LIST_ERROR = "GET_COUNTRY_LIST_ERROR"

export const GET_PLAN_LIST_REQUEST = "GET_PLAN_LIST_REQUEST"
export const GET_PLAN_LIST_SUCCESS = "GET_PLAN_LIST_SUCCESS"
export const GET_PLAN_LIST_ERROR = "GET_PLAN_LIST_ERROR"

export const GET_SPECILIZATION_LIST_REQUEST = "GET_SPECILIZATION_LIST_REQUEST"
export const GET_SPECILIZATION_LIST_SUCCESS = "GET_SPECILIZATION_LIST_SUCCESS"
export const GET_SPECILIZATION_LIST_ERROR = "GET_SPECILIZATION_LIST_ERROR"

export const ADD_SPECILIZATION_REQUEST = "ADD_SPECILIZATION_REQUEST"
export const ADD_SPECILIZATION_SUCCESS = "ADD_SPECILIZATION_SUCCESS"
export const ADD_SPECILIZATION_ERROR = "ADD_SPECILIZATION_ERROR"

export const GET_UPDATE_SPECILIZATION_REQUEST = "GET_UPDATE_SPECILIZATION_REQUEST"
export const GET_UPDATE_SPECILIZATION_SUCCESS = "GET_UPDATE_SPECILIZATION_SUCCESS"
export const GET_UPDATE_SPECILIZATION_ERROR = "GET_UPDATE_SPECILIZATION_ERROR"

export const GET_SPECILIZATION_CHANGE_STATUS_REQUEST = "GET_SPECILIZATION_CHANGE_STATUS_REQUEST"
export const GET_SPECILIZATION_CHANGE_STATUS_SUCCESS = "GET_SPECILIZATION_CHANGE_STATUS_SUCCESS"
export const GET_SPECILIZATION_CHANGE_STATUS_ERROR = "GET_SPECILIZATION_CHANGE_STATUS_ERROR"

export const GET_ADD_FAQ_REQUEST = "GET_ADD_FAQ_REQUEST"
export const GET_ADD_FAQ_SUCCESS = "GET_ADD_FAQ_SUCCESS"
export const GET_ADD_FAQ_ERROR = "GET_ADD_FAQ_ERROR"

export const GET_UPDATE_FAQ_REQUEST = "GET_UPDATE_FAQ_REQUEST"
export const GET_UPDATE_FAQ_SUCCESS = "GET_UPDATE_FAQ_SUCCESS"
export const GET_UPDATE_FAQ_ERROR = "GET_UPDATE_FAQ_ERROR"

export const GET_FAQ_CHANGE_STATUS_REQUEST = "GET_FAQ_CHANGE_STATUS_REQUEST"
export const GET_FAQ_CHANGE_STATUS_SUCCESS = "GET_FAQ_CHANGE_STATUS_SUCCESS"
export const GET_FAQ_CHANGE_STATUS_ERROR = "GET_FAQ_CHANGE_STATUS_ERROR"

export const GET_FAQ_LIST_REQUEST = "GET_FAQ_LIST_REQUEST"
export const GET_FAQ_LIST_SUCCESS = "GET_FAQ_LIST_SUCCESS"
export const GET_FAQ_LIST_ERROR = "GET_FAQ_LIST_ERROR"

export const GET_ADD_EDUCATOR_REQUEST = "GET_ADD_EDUCATOR_REQUEST"
export const GET_ADD_EDUCATOR_SUCCESS = "GET_ADD_EDUCATOR_SUCCESS"
export const GET_ADD_EDUCATOR_ERROR = "GET_ADD_EDUCATOR_ERROR"

export const GET_UPDATE_EDUCATOR_REQUEST = "GET_UPDATE_EDUCATOR_REQUEST"
export const GET_UPDATE_EDUCATOR_SUCCESS = "GET_UPDATE_EDUCATOR_SUCCESS"
export const GET_UPDATE_EDUCATOR_ERROR = "GET_UPDATE_EDUCATOR_ERROR"

export const GET_EDUCATOR_LIST_REQUEST = "GET_EDUCATOR_LIST_REQUEST"
export const GET_EDUCATOR_LIST_SUCCESS = "GET_EDUCATOR_LIST_SUCCESS"
export const GET_EDUCATOR_LIST_ERROR = "GET_EDUCATOR_LIST_ERROR"

export const GET_EDUCATOR_CHANGE_STATUS_REQUEST = "GET_EDUCATOR_CHANGE_STATUS_REQUEST"
export const GET_EDUCATOR_CHANGE_STATUS_SUCCESS = "GET_EDUCATOR_CHANGE_STATUS_SUCCESS"
export const GET_EDUCATOR_CHANGE_STATUS_ERROR = "GET_EDUCATOR_CHANGE_STATUS_ERROR"

export const GET_UPDATE_LINK_REQUEST = "GET_UPDATE_LINK_REQUEST"
export const GET_UPDATE_LINK_SUCCESS = "GET_UPDATE_LINK_SUCCESS"
export const GET_UPDATE_LINK_ERROR = "GET_UPDATE_LINK_ERROR"

export const GET_ADD_LINK_REQUEST = "GET_ADD_LINK_REQUEST"
export const GET_ADD_LINK_SUCCESS = "GET_ADD_LINK_SUCCESS"
export const GET_ADD_LINK_ERROR = "GET_ADD_LINK_ERROR"


export const GET_LINK_LIST_REQUEST = "GET_LINK_LIST_REQUEST"
export const GET_LINK_LIST_SUCCESS = "GET_LINK_LIST_SUCCESS"
export const GET_LINK_LIST_ERROR = "GET_LINK_LIST_ERROR"

export const GET_LINK_CHANGE_STATUS_REQUEST = "GET_LINK_CHANGE_STATUS_REQUEST"
export const GET_LINK_CHANGE_STATUS_SUCCESS = "GET_LINK_CHANGE_STATUS_SUCCESS"
export const GET_LINK_CHANGE_STATUS_ERROR = "GET_LINK_CHANGE_STATUS_ERROR"


export const GET_LANGUAGE_LIST_REQUEST = "GET_LANGUAGE_LIST_REQUEST"
export const GET_LANGUAGE_LIST_SUCCESS = "GET_LANGUAGE_LIST_SUCCESS"
export const GET_LANGUAGE_LIST_ERROR = "GET_LANGUAGE_LIST_ERROR"

export const GET_LANGUAGE_CHANGE_STATUS_REQUEST = "GET_LANGUAGE_CHANGE_STATUS_REQUEST"
export const GET_LANGUAGE_CHANGE_STATUS_SUCCESS = "GET_LANGUAGE_CHANGE_STATUS_SUCCESS"
export const GET_LANGUAGE_CHANGE_STATUS_ERROR = "GET_LANGUAGE_CHANGE_STATUS_ERROR"


export const POST_ADD_PLAN_REQUEST = "POST_ADD_PLAN_REQUEST"
export const GET_ADD_PLAN_SUCCESS = "GET_ADD_PLAN_SUCCESS"
export const GET_ADD_PLAN_ERROR = "GET_ADD_PLAN_ERROR"

export const POST_UPDATE_PLAN_REQUEST = "POST_UPDATE_PLAN_REQUEST"
export const GET_UPDATE_PLAN_SUCCESS = "GET_UPDATE_PLAN_SUCCESS"
export const GET_UPDATE_PLAN_ERROR = "GET_UPDATE_PLAN_ERROR"

export const GET_PLAN_CHANGE_STATUS_REQUEST = "GET_PLAN_CHANGE_STATUS_REQUEST"
export const GET_PLAN_CHANGE_STATUS_SUCCESS = "GET_PLAN_CHANGE_STATUS_SUCCESS"
export const GET_PLAN_CHANGE_STATUS_ERROR = "GET_PLAN_CHANGE_STATUS_ERROR"


export const POST_ADD_CLINIC_REQUEST = "POST_ADD_CLINIC_REQUEST"
export const GET_ADD_CLINIC_SUCCESS = "GET_ADD_CLINIC_SUCCESS"
export const GET_ADD_CLINIC_ERROR = "GET_ADD_CLINIC_ERROR"

export const POST_UPDATE_CLINIC_REQUEST = "POST_UPDATE_CLINIC_REQUEST"
export const GET_UPDATE_CLINIC_SUCCESS = "GET_UPDATE_CLINIC_SUCCESS"
export const GET_UPDATE_CLINIC_ERROR = "GET_UPDATE_CLINIC_ERROR"

export const GET_ADD_KNOWLEDGE_REQUEST = "GET_ADD_KNOWLEDGE_REQUEST"
export const GET_ADD_KNOWLEDGE_SUCCESS = "GET_ADD_KNOWLEDGE_SUCCESS"
export const GET_ADD_KNOWLEDGE_ERROR = "GET_ADD_KNOWLEDGE_ERROR"

export const GET_UPDATE_KNOWLEDGE_REQUEST = "GET_UPDATE_KNOWLEDGE_REQUEST"
export const GET_UPDATE_KNOWLEDGE_SUCCESS = "GET_UPDATE_KNOWLEDGE_SUCCESS"
export const GET_UPDATE_KNOWLEDGE_ERROR = "GET_UPDATE_KNOWLEDGE_ERROR"

export const GET_KNOWLEDGE_LIST_REQUEST = "GET_KNOWLEDGE_LIST_REQUEST"
export const GET_KNOWLEDGE_LIST_SUCCESS = "GET_KNOWLEDGE_LIST_SUCCESS"
export const GET_KNOWLEDGE_LIST_ERROR = "GET_KNOWLEDGE_LIST_ERROR"

export const GET_KNOWLEDGE_CHANGE_STATUS_REQUEST = "GET_KNOWLEDGE_CHANGE_STATUS_REQUEST"
export const GET_KNOWLEDGE_CHANGE_STATUS_SUCCESS = "GET_KNOWLEDGE_CHANGE_STATUS_SUCCESS"
export const GET_KNOWLEDGE_CHANGE_STATUS_ERROR = "GET_KNOWLEDGE_CHANGE_STATUS_ERROR"

export const POST_UPLOAD_FILE_REQUEST = "POST_UPLOAD_FILE_REQUEST"
export const GET_UPLOAD_FILE_SUCCESS = "GET_UPLOAD_FILE_SUCCESS"
export const GET_UPLOAD_FILE_ERROR = "GET_UPLOAD_FILE_ERROR"

export const POST_ADD_CLINIC_SUBSCRIPTION_REQUEST = "POST_ADD_CLINIC_SUBSCRIPTION_REQUEST"
export const GET_ADD_CLINIC_SUBSCRIPTION_SUCCESS = "GET_ADD_CLINIC_SUBSCRIPTION_SUCCESS"
export const GET_ADD_CLINIC_SUBSCRIPTION_ERROR = "GET_ADD_CLINIC_SUBSCRIPTION_ERROR"

export const POST_UPDATE_CLINIC_SUBSCRIPTION_REQUEST = "POST_UPDATE_CLINIC_SUBSCRIPTION_REQUEST"
export const GET_UPDATE_CLINIC_SUBSCRIPTION_SUCCESS = "GET_UPDATE_CLINIC_SUBSCRIPTION_SUCCESS"
export const GET_UPDATE_CLINIC_SUBSCRIPTION_ERROR = "GET_UPDATE_CLINIC_SUBSCRIPTION_ERROR"

export const GET_CLINIC_CALENDAR_LIST_REQUEST = "GET_CLINIC_CALENDAR_LIST_REQUEST"
export const GET_CLINIC_CALENDAR_LIST_SUCCESS = "GET_CLINIC_CALENDAR_LIST_SUCCESS"
export const GET_CLINIC_CALENDAR_LIST_ERROR = "GET_CLINIC_CALENDAR_LIST_ERROR"

export const POST_ADD_CLINIC_CALENDAR_REQUEST = "POST_ADD_CLINIC_CALENDAR_REQUEST"
export const GET_ADD_CLINIC_CALENDAR_SUCCESS = "GET_ADD_CLINIC_CALENDAR_SUCCESS"
export const GET_ADD_CLINIC_CALENDAR_ERROR = "GET_ADD_CLINIC_CALENDAR_ERROR"

export const GET_CLINIC_ACTIVE_LIST_REQUEST = "GET_CLINIC_ACTIVE_LIST_REQUEST"
export const GET_CLINIC_ACTIVE_LIST_SUCCESS = "GET_CLINIC_ACTIVE_LIST_SUCCESS"
export const GET_CLINIC_ACTIVE_LIST_ERROR = "GET_CLINIC_ACTIVE_LIST_ERROR"

export const GET_CATEGORY_LIST_REQUEST = "GET_CATEGORY_LIST_REQUEST"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR"

export const GET_CALENDAR_CHANGE_STATUS_REQUEST = "GET_CALENDAR_CHANGE_STATUS_REQUEST"
export const GET_CALENDAR_CHANGE_STATUS_SUCCESS = "GET_CALENDAR_CHANGE_STATUS_SUCCESS"
export const GET_CALENDAR_CHANGE_STATUS_ERROR = "GET_CALENDAR_CHANGE_STATUS_ERROR"

export const GET_COMPANY_LIST_REQUEST = "GET_COMPANY_LIST_REQUEST"
export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS"
export const GET_COMPANY_LIST_ERROR = "GET_COMPANY_LIST_ERROR"

export const POST_ADD_COMPANY_REQUEST = "POST_ADD_COMPANY_REQUEST"
export const GET_ADD_COMPANY_SUCCESS = "GET_ADD_COMPANY_SUCCESS"
export const GET_ADD_COMPANY_ERROR = "GET_ADD_COMPANY_ERROR"

export const GET_COMPANY_CHANGE_STATUS_REQUEST = "GET_COMPANY_CHANGE_STATUS_REQUEST"
export const GET_COMPANY_CHANGE_STATUS_SUCCESS = "GET_COMPANY_CHANGE_STATUS_SUCCESS"
export const GET_COMPANY_CHANGE_STATUS_ERROR = "GET_COMPANY_CHANGE_STATUS_ERROR"

export const POST_UPDATE_COMPANY_REQUEST = "POST_UPDATE_COMPANY_REQUEST"
export const GET_UPDATE_COMPANY_SUCCESS = "GET_UPDATE_COMPANY_SUCCESS"
export const GET_UPDATE_COMPANY_ERROR = "GET_UPDATE_COMPANY_ERROR"

export const ADD_RCM_TYPE_REQUEST = "ADD_RCM_TYPE_REQUEST"
export const ADD_RCM_TYPE_SUCCESS = "ADD_RCM_TYPE_SUCCESS"
export const ADD_RCM_TYPE_ERROR = "ADD_RCM_TYPE_ERROR"

export const RCM_TYPE_LIST_REQUEST = "RCM_TYPE_LIST_REQUEST"
export const RCM_TYPE_LIST_SUCCESS = "RCM_TYPE_LIST_SUCCESS"
export const RCM_TYPE_LIST_ERROR = "RCM_TYPE_LIST_ERROR"

export const DELETE_RCM_TYPE_REQUEST = "DELETE_RCM_TYPE_REQUEST"
export const DELETE_RCM_TYPE_SUCCESS = "DELETE_RCM_TYPE_SUCCESS"
export const DELETE_RCM_TYPE_ERROR = "DELETE_RCM_TYPE_ERROR"

export const GET_DASHBOARD_REQUEST = "GET_DASHBOARD_REQUEST"
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS"
export const GET_DASHBOARD_ERROR = "GET_DASHBOARD_ERROR"
